#!/usr/bin/env python3

# Copyright (C) 2020 Morten Eek

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys, psutil, xmlrpc.client, gi
# gi.require_version('Wnck', '3.0')
# from gi.repository import Wnck
gi.require_version('Gdk', '3.0')
from gi.repository import Gdk
sys.path.append('bin')
from bin.app import App




def getWindow(pid):
    found = False
    for window in windowList:
        if window.get_pid() == pid:
            found = True
            return window

    if not found:
        return None


def is_running(script): # WAIT: Bare sjekke om får kontakt med serverproxy heller?
    for p in psutil.process_iter():
        if p.name().startswith('python'):
            if len(p.cmdline())>1 and script in p.cmdline()[1] and p.pid !=os.getpid():
                return str(p.pid)


def open_files(args, app):
    if len(args) > 1:
        for file in sys.argv[1:]:
            if os.path.isfile(file):
                app.run_command('open_file', file)


if __name__ == "__main__":
    port = 9000
    pid = is_running(os.path.basename(__file__))
    if pid:
        app = xmlrpc.client.ServerProxy('http://localhost:' + str(port))
        open_files(sys.argv, app)
        # app.run_command('focus_app')
        

        # display = Gdk.Display.get_default()
        # screen = display.get_default_screen()
        # workspace = Gdk.Display.get_current_desktop ()
        # # windowList = screen.get_windows()  

        # for window in windowList:
        #     if window.get_pid() == pid:
        #         print('fdsaf')

    else:            
        app = App()
        app.build_ui()

        for r, d, f in os.walk(app.model.tmp_dir):
            for file in f:
                if 'Untitled-' in file:
                    app.run_command('open_file', app.model.tmp_dir + '/' + file)

        app.run_command('show_welcome')
        open_files(sys.argv, app)
        app.run(port)

