#!/usr/bin/env python3

# Copyright (C) 2020 Morten Eek

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
sys.path.append('bin')

import os, psutil
from app import App

def is_running(script):
    for p in psutil.process_iter():
        if p.name().startswith('python'):
            if len(p.cmdline())>1 and script in p.cmdline()[1] and p.pid !=os.getpid():
                print(p.pid)
                return True
    return False


if __name__ == "__main__":
    # TODO: Legg inn if else når lagt til pyro4
    running = is_running(os.path.basename(__file__))
    # if running:
    # else:   
    #      
    app = App()
    app.build_ui()

    for r, d, f in os.walk(app.model.tmp_dir):
        for file in f:
            if 'Untitled-' in file:
                app.run_command('open_file', app.model.tmp_dir + '/' + file)

    app.run_command('show_welcome')

    if len(sys.argv) > 1:
        for file in sys.argv[1:]:
            if os.path.isfile(file):
                app.run_command('open_file', file)

    app.run(running)